#!/usr/bin/env sh

# Check for instable code (Larastan)
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo " <> [PHPStan] - Instable code detected.";
    exit 1;
fi;

# Format modified files (Laravel Pint)
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}"
done;
